# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "everydayrails-4.0"
  
  config.vm.box = "ubuntu120403ja"
  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end

  config.omnibus.chef_version = :latest


  config.vm.provision :chef_solo do |chef|
    chef.json = {
      rbenv: {
        user_installs: [{
          user: "vagrant",
          rubies: ["2.0.0-p451"],
          global: "2.0.0-p451",
          gems: {
            "2.0.0-p451" => [
              { name: "bundler"
              }
            ]
          }
        }]
      }
    }

    chef.cookbooks_path = ["./chef-repo/cookbooks", "./chef-repo/site-cookbooks"]

    chef.run_list = [
      "apt",
      "base",
      "ruby_build",
      "rbenv::user",
      "sublime-text"
    ]
  end
end
